@Host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyOSwiaWF0IjoxNzMwNDYzNTE3fQ.wyXOG1qxI7fe0xUpEcbIThGvrdiam9Q2Z9jK4O3_ZCY

///////////////////// USERS //////////////////////
// Get all users
###
GET {{Host}}/api/users/

// Get User By ID
###
GET {{Host}}/api/users/4

// Register user
###
POST {{Host}}/api/users/register
content-type: application/json

{
    "username": "lkjasd",
    "password": "00000"
}

// Login user
###
POST {{Host}}/api/users/login
content-type: application/json

{
    "username": "lkjasd",
    "password": "00000"
}

### Perfil
GET {{Host}}/api/users/perfil
Authorization: {{token}}


///////////////////// EVENTS //////////////////////
// Get all events
###
GET {{Host}}/api/events/

// Get event by id
###
GET {{Host}}/api/events/33

// Post event
###
POST {{Host}}/api/events/
Authorization: {{token}}
content-type: application/json

{
    "nombre": "Cosas",
    "descripcion": "Cosas de cosas.",
    "fecha": "2026-05-01",
    "ubicacion": "Satanderº",
    "tipoDeporte": "Cosas",
    "organizador": "organizador113"
}

// Update event
###
PUT {{Host}}/api/events/57
Authorization: {{token}}
content-type: application/json

{
    "nombre": "Carrera",
    "descripcion": "Carrera de montaña.",
    "fecha": "2025-05-01",
    "ubicacion": "Bilbao",
    "tipoDeporte": "Senderismo",
    "organizador": "organizador33"
}

// Delete event
###
DELETE {{Host}}/api/events/57
Authorization: {{token}}



///////// CONSULTAS AVANZADAS //////////

// Get upcoming events
###
GET {{Host}}/api/events/upcoming

// Get events by type
###
GET {{Host}}/api/events/type?type=senderismo

// Get events by date
###
GET {{Host}}/api/events/date?from=2023-09-10&to=2023-09-20